# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5a8d7337ee2ad81d7402ecbdddf3b9253ab5b19a622cbf82dc2e46824fd71b54cff64f5d4ed23472318d1ea355b6c71fd6562473da23b45f9fc9e113a19f8cb

test:
  secret_key_base: 7d8de81dfdd7a9ccb740a4a71609189da1320851f44af481cfb247ea642abae3e3a773bcc81765c2075538913e63e427d6491db4928db6dc10e28863d7c7b054

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
